//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scradic.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scradic.Utils.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the command or word you want to search/translate:.
        /// </summary>
        public static string EnterWordToSearchTranslate_Ask {
            get {
                return ResourceManager.GetString("EnterWordToSearchTranslate_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no words available. The list is empty..
        /// </summary>
        public static string NoWordsAvailable {
            get {
                return ResourceManager.GetString("NoWordsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must insert only numeric characters..
        /// </summary>
        public static string OnlyNumericCharacters {
            get {
                return ResourceManager.GetString("OnlyNumericCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF files in the folder:.
        /// </summary>
        public static string Pdf_Files {
            get {
                return ResourceManager.GetString("Pdf_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder does not exist..
        /// </summary>
        public static string PdfFolderDoesNotExist {
            get {
                return ResourceManager.GetString("PdfFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No PDF files found in the folder..
        /// </summary>
        public static string PdfFolderEmpty {
            get {
                return ResourceManager.GetString("PdfFolderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDF index does not exist, please enter a valid one..
        /// </summary>
        public static string PdfIndexDoesNotExist {
            get {
                return ResourceManager.GetString("PdfIndexDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF has been created successfully. Do you want to open it?.
        /// </summary>
        public static string SavePdf_Ask {
            get {
                return ResourceManager.GetString("SavePdf_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of the PDF you want to open (0 to exit):.
        /// </summary>
        public static string SeePdf_Ask {
            get {
                return ResourceManager.GetString("SeePdf_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error, please try again..
        /// </summary>
        public static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the word.
        /// </summary>
        public static string WordToPdf_Ask_1 {
            get {
                return ResourceManager.GetString("WordToPdf_Ask_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to PDF file? .
        /// </summary>
        public static string WordToPdf_Ask_2 {
            get {
                return ResourceManager.GetString("WordToPdf_Ask_2", resourceCulture);
            }
        }
    }
}
